name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build React application
      run: npm run build
    
    - name: Build Windows executable
      run: npm run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: List dist directory
      run: dir dist
    
    - name: Upload Windows Portable
      uses: actions/upload-artifact@v3
      with:
        name: Contract-Generator-Windows-Portable
        path: dist/*.exe
        if-no-files-found: error
    
    - name: Upload all Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Contract-Generator-Windows-All
        path: dist/*
        if-no-files-found: warn
